# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SignPath - Code Signing simple and secure
url: "https://about.signpath.io"
email_sales: sales@signpath.io?subject=Enterprise%20subscription
email_oss: support@signpath.io?subject=OSS%20subscription
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

toc:
  min_level: 1
  max_level: 2
permalink: /blog/:year/:month/:day/:title.html

include: 
  - .well-known
# used for Microsoft OpenID Connect App

exclude:
  - Gemfile
  - Gemfile.lock
  - assets/icons/single
  - README.md
  - TODO.txt
  - set-environment.ps1
  - deploy-to-fq1.ps1
  - CNAME

sass:
    style: compressed